---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: VSC, VASA Provider und SRA Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes.html"
  - title: Schnellstart
    url: "/qsg.html"
  - section: deploy
  - section: manage
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
