---
permalink: deploy/concept-migration-of-disaster-recovery-setup-from-windows-to-appliance.html 
sidebar: sidebar 
keywords: migration, windows, SRM, appliance, 
summary: 'Wenn Sie Windows-basierten Site Recovery Manager (SRM) für Disaster Recovery verwenden und die SRM-Appliance für dasselbe Setup verwenden möchten, sollten Sie Ihr Windows Disaster Recovery-Setup auf die Appliance-basierte SRM migrieren.' 
---
= Migration von Windows SRM auf eine SRM Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Windows-basierten Site Recovery Manager (SRM) für Disaster Recovery verwenden und die SRM-Appliance für dasselbe Setup verwenden möchten, sollten Sie Ihr Windows Disaster Recovery-Setup auf die Appliance-basierte SRM migrieren.

Bei der Migration der Disaster Recovery sind folgende Schritte zu beachten:

. Aktualisieren Sie Ihre vorhandene virtuelle Appliance für VSC, VASA Provider und SRA auf Version 9.7.1.
+
link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Upgrade auf die virtuelle 9.7.1 Appliance für VSC, VASA Provider und SRA"^]

. Migrieren von Windows-basiertem Storage Replication Adapter auf Appliance-basierte SRA
. Migration von Windows SRM-Daten zu einer SRM-Appliance


https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-F39A84D3-2E3D-4018-97DD-5D7F7E041B43.html["Klicken Sie hier"^] Für detaillierte Schritte.
