---
permalink: deploy/concept-configure-vsc-for-vmware-vsphere-environment.html 
sidebar: sidebar 
keywords: configuring, your, virtual, storage, console, vmware, vsphere, environment, 
summary: '(VSC) unterstützt zahlreiche Umgebungen. Einige Funktionen in diesen Umgebungen erfordern möglicherweise zusätzliche Konfigurationen.' 
---
= Konfigurieren Sie Ihre Virtual Storage Console für VMware vSphere Umgebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
(VSC) unterstützt zahlreiche Umgebungen. Einige Funktionen in diesen Umgebungen erfordern möglicherweise zusätzliche Konfigurationen.

Möglicherweise müssen Sie einige der folgenden Aufgaben durchführen, um Ihre ESXi Hosts, Gastbetriebssysteme und VSC zu konfigurieren:

* Überprüfen der ESXi-Hosteinstellungen, einschließlich der UNMAP-Einstellungen
* Hinzufügen von Timeout-Werten für Gastbetriebssysteme
* Erneutes Generieren des VSC SSL-Zertifikats
* Erstellung von Storage-Funktionsprofilen und Schwellenwertwarnungen
* Ändern der Preferences-Datei, um das Mounten von Datastores über verschiedene Subnetze zu ermöglichen

