---
permalink: deploy/task-add-storage-systems.html 
sidebar: sidebar 
keywords: adding, storage, systems, vsc, 
summary: 'Sie können Storage-System manuell zur Virtual Storage Console (VSC) hinzufügen.' 
---
= Fügen Sie Storage-Systeme zur VSC hinzu
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Storage-System manuell zur Virtual Storage Console (VSC) hinzufügen.

.Über diese Aufgabe
Jedes Mal, wenn Sie starten (VSC) oder wählen Sie die Option *ALLE* WIEDERENTDECKEN, erkennt VSC automatisch die verfügbaren Speichersysteme.

.Schritte
. Fügen Sie zur VSC ein Storage-System über die VSC Startseite hinzu:
+
** Klicken Sie auf Menü:Speichersysteme[Hinzufügen].
** Klicken Sie auf Menü:Übersicht[erste Schritte] und dann auf die Schaltfläche *HINZUFÜGEN* unter *Speichersystem hinzufügen*.


. Geben Sie im Dialogfeld *Storage-System hinzufügen* die Management-IP-Adresse und die Anmeldeinformationen für dieses Speichersystem ein.
+
Sie können auch Speichersysteme hinzufügen, indem Sie die IPv6-Adresse des Clusters oder verwenden. In diesem Dialogfeld können Sie außerdem die Standardwerte für TLS und die Portnummer ändern.

+
Wenn Sie Speicher von der VSC *Storage System* Seite hinzufügen, müssen Sie auch die vCenter Server Instanz angeben, wo sich der Speicher befindet. Das Dialogfeld *Storage-System hinzufügen* enthält eine Dropdown-Liste der verfügbaren vCenter Server-Instanzen. Die VSC zeigt diese Option nicht an, wenn Sie einem Rechenzentrum Storage hinzufügen, das bereits einer vCenter Server-Instanz zugeordnet ist.

. Klicken Sie auf *OK*, nachdem Sie alle erforderlichen Informationen hinzugefügt haben.

