---
permalink: deploy/task-run-the-gos-timeout-scripts-for-windows.html 
sidebar: sidebar 
keywords: setting, timeout, values, windows, guest, operating, systems, 
summary: 'Die Timeout-Skripte des Gastbetriebssystems (OS) legen die SCSI I/O Timeout-Einstellungen für Windows Gastbetriebssysteme fest. Sie können entweder eine Zeitüberschreitung von 60 Sekunden oder eine Zeitüberschreitung von 190 Sekunden angeben. Sie müssen das Windows Gast-Betriebssystem neu booten, damit die Einstellungen wirksam werden.' 
---
= Legen Sie die Zeitüberschreitungswerte für Windows Gastbetriebssysteme fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Timeout-Skripte des Gastbetriebssystems (OS) legen die SCSI I/O Timeout-Einstellungen für Windows Gastbetriebssysteme fest. Sie können entweder eine Zeitüberschreitung von 60 Sekunden oder eine Zeitüberschreitung von 190 Sekunden angeben. Sie müssen das Windows Gast-Betriebssystem neu booten, damit die Einstellungen wirksam werden.

.Bevor Sie beginnen
Sie müssen das ISO-Image mit dem Windows-Skript angehängt haben.

.Schritte
. Greifen Sie auf die Konsole der virtuellen Windows-Maschine zu und melden Sie sich bei einem Konto mit Administratorrechten an.
. Wenn das Skript nicht automatisch startet, öffnen Sie das CD-Laufwerk, und führen Sie dann den aus `windows_gos_timeout.reg` Skript:
+
Das Dialogfeld Registry-Editor wird angezeigt.

. Klicken Sie auf *Ja*, um fortzufahren.
+
Die folgende Meldung wird angezeigt: `The keys and values contained in D:\windows_gos_timeout.reg have been successfully added to the registry.`

. Starten Sie das Windows Gastbetriebssystem neu.
. Heben Sie die Bereitstellung des ISO-Images auf.

