---
permalink: deploy/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, storage, systems, 
summary: Sie können die virtuelle Speicherkonsole für VMware vSphere verwenden, um Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festzulegen. 
---
= Legen Sie die Standardanmeldeinformationen für Speichersysteme fest
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die virtuelle Speicherkonsole für VMware vSphere verwenden, um Standardanmeldeinformationen für ein Speichersystem in Ihrem vCenter Server festzulegen.

Sie müssen den vCenter Server ausgewählt haben, den Sie zum Erstellen von Standardanmeldeinformationen verwenden möchten.

Wenn Sie Standardanmeldeinformationen für Storage-Systeme einrichten, verwendet (VSC) diese Zugangsdaten, um sich in einem Storage-System anzumelden, das die VSC gerade erkannt hat. Wenn die Standardanmeldeinformationen nicht funktionieren, müssen Sie sich manuell beim Speichersystem anmelden. VSC und SRA unterstützen das Hinzufügen von Anmeldeinformationen des Storage-Systems auf Cluster-Ebene oder -Ebene. Vasa Provider kann aber nur mit Anmeldedaten auf Cluster-Ebene arbeiten.

.Schritte
. Klicken Sie auf der VSC *Home* Seite auf Menü:Einstellungen[Administratoreinstellungen > Standardanmeldedaten für Storage-System konfigurieren].
. Geben Sie im Dialogfeld *Speichersystemstandard-Anmeldeinformationen* den Benutzernamen und das Kennwort für das Speichersystem ein.
+
Storage Controller-Anmeldedaten werden in ONTAP basierend auf dem Benutzernamen und dem Passwort-Paar zugewiesen. Die Zugangsdaten für den Storage Controller können entweder das Administratorkonto oder ein benutzerdefiniertes Konto, das die rollenbasierte Zugriffssteuerung verwendet.

+
Sie können die Rollen, die dem Benutzernamen und Passwort des Storage Controllers zugeordnet sind, nicht mit VSC ändern. Zum Ändern oder Erstellen einer neuen ONTAP Benutzerrolle zur Verwendung mit der virtuellen Appliance für VSC, VASA Provider und SRA können Sie System Manager verwenden.

+
Weitere Informationen finden Sie im Abschnitt „`Konfigurieren von Benutzerrollen und -Berechtigungen`“ im Handbuch „_Virtual Storage Console, VASA Provider und Storage Replication Adapter für VMware® vSphere Deployment and Setup Guide for 9.7 Release_.

. Klicken Sie auf *OK*, um die Standardanmeldeinformationen zu speichern.


Wenn Sie die Anmeldedaten des Speichersystems aktualisiert haben, weil ein Speichersystem den Status „`Authentifizierungsfehler`“ gemeldet hat, klicken Sie auf die Option *ALLE WIEDERERKENNEN*, die auf der Seite Speichersysteme verfügbar ist. Ist dies der Fall, versucht die VSC mithilfe der neuen Zugangsdaten, sich mit dem Storage-System zu verbinden.
