---
permalink: deploy/task-run-the-gos-timeout-scripts-for-rhel4-or-sles9.html 
sidebar: sidebar 
keywords: setting, timeout, values, linux, guest, operating, systems, 
summary: 'Die Timeout-Skripte des Gastbetriebssystems (OS) stellen die SCSI-I/O-Zeitüberschreitungseinstellungen für die Versionen 4, 5, 6 und 7 von Red hat Enterprise Linux sowie 9, 10 und 11 von SUSE Linux Enterprise Server ein. Sie können entweder eine Zeitüberschreitung von 60 Sekunden oder eine Zeitüberschreitung von 190 Sekunden angeben. Sie müssen das Skript jedes Mal ausführen, wenn Sie auf eine neue Linux-Version aktualisieren.' 
---
= Legen Sie Timeout-Werte für Linux Gast-Betriebssysteme fest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Timeout-Skripte des Gastbetriebssystems (OS) stellen die SCSI-I/O-Zeitüberschreitungseinstellungen für die Versionen 4, 5, 6 und 7 von Red hat Enterprise Linux sowie 9, 10 und 11 von SUSE Linux Enterprise Server ein. Sie können entweder eine Zeitüberschreitung von 60 Sekunden oder eine Zeitüberschreitung von 190 Sekunden angeben. Sie müssen das Skript jedes Mal ausführen, wenn Sie auf eine neue Linux-Version aktualisieren.

.Bevor Sie beginnen
Sie müssen das ISO-Image mit dem Linux-Skript angehängt haben.

.Schritte
. Greifen Sie auf die Konsole der virtuellen Linux-Maschine zu und melden Sie sich bei einem Konto mit Root-Berechtigungen an.
. Führen Sie die aus `linux_gos_timeout-install.sh` Skript:
+
Für Red hat Enterprise Linux 4 oder SUSE Linux Enterprise Server 9 wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
Restarting udev... this may take a few seconds.
----
+
[listing]
----
Setting I/O Timeout (60s) for /dev/sda - SUCCESS!
----
+
Für Red hat Enterprise Linux 5, Red hat Enterprise Linux 6 und Red hat Enterprise Linux 7 wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
patching file /etc/udev/rules.d/50-udev.rules
----
+
[listing]
----
Hunk #1 succeeded at 333 (offset 13 lines).
----
+
[listing]
----
Restarting udev... this may take a few seconds.
----
+
[listing]
----
Starting udev: [ OK ]
----
+
[listing]
----
Setting I/O Timeout (60s) for /dev/sda - SUCCESS!
----
+
Für SUSE Linux Enterprise Server 10 oder SUSE Linux Enterprise Server 11 wird eine Meldung wie die folgende angezeigt:

+
[listing]
----
patching file /etc/udev/rules.d/50-udev-default.rules
----
+
[listing]
----
Hunk #1 succeeded at 114 (offset 1 line).
----
+
[listing]
----
Restarting udev ...this may take a few seconds.
----
+
[listing]
----
Updating all available device nodes in /dev:   done
----
. Heben Sie die Bereitstellung des ISO-Images auf.

