---
permalink: deploy/task-regenerate-an-ssl-certificate-for-vsc.html 
sidebar: sidebar 
keywords: regenerating, ssl, certificate, virtual, storage, console, 
summary: 'Das SSL-Zertifikat wird bei der Installation (VSC) generiert. Der Distinguished Name (DN), der für das SSL-Zertifikat generiert wird, ist möglicherweise kein allgemeiner Name (CN), den die Clientcomputer erkennen. Durch Ändern der Passwörter für den Schlüsselspeicher und den privaten Schlüssel können Sie das Zertifikat erneut generieren und ein standortspezifisches Zertifikat erstellen.' 
---
= Erstellen Sie ein SSL-Zertifikat für die virtuelle Speicherkonsole erneut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SSL-Zertifikat wird bei der Installation (VSC) generiert. Der Distinguished Name (DN), der für das SSL-Zertifikat generiert wird, ist möglicherweise kein allgemeiner Name (CN), den die Clientcomputer erkennen. Durch Ändern der Passwörter für den Schlüsselspeicher und den privaten Schlüssel können Sie das Zertifikat erneut generieren und ein standortspezifisches Zertifikat erstellen.

Sie können die Remote-Diagnose mit der Wartungskonsole aktivieren und standortspezifisches Zertifikat generieren.

https://kb.netapp.com/app/answers/answer_view/a_id/1075654["Antwort der NetApp Knowledgebase 1075654: Virtual Storage Console 7.x: Implementierung von CA-signierten Zertifikaten"^]

.Schritte
. Melden Sie sich bei der Wartungskonsole an.
. Eingabe `1` Für den Zugriff auf `Application Configuration` Menü.
. Im `Application Configuration` Menü, ENTER `3` Um den VSC Service zu beenden.
. Eingabe `7` Um das SSL-Zertifikat erneut zu generieren.

