---
permalink: manage/task-monitor-datastores-using-the-traditional-dashboard.html 
sidebar: sidebar 
keywords: monitoring, datastores, virtual, machines, using, the, traditional, dashboard, 
summary: Mithilfe des herkömmlichen Dashboards der virtuellen Appliance für Virtual Storage Console, VASA Provider und Storage Replication Adapter können Sie die herkömmlichen Datastores und Virtual Machines überwachen. Mit den Dashboard-Daten können Sie die Datenspeicherauslastung analysieren und Korrekturmaßnahmen ergreifen, um zu verhindern, dass die Virtual Machines mit speicherbezogenen Einschränkungen umgehen. 
---
= Überwachen Sie Datastores und Virtual Machines mit dem herkömmlichen Dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe des herkömmlichen Dashboards der virtuellen Appliance für Virtual Storage Console, VASA Provider und Storage Replication Adapter können Sie die herkömmlichen Datastores und Virtual Machines überwachen. Mit den Dashboard-Daten können Sie die Datenspeicherauslastung analysieren und Korrekturmaßnahmen ergreifen, um zu verhindern, dass die Virtual Machines mit speicherbezogenen Einschränkungen umgehen.

Wählen Sie im Dialogfeld Storage-I/O-Steuerung konfigurieren die Option *Storage-I/O-Steuerung aktivieren und Statistiken sammeln* oder *Storage-I/O-Steuerung deaktivieren, aber Statistiksammlung aktivieren* aus. Sie können Storage I/O Control nur aktivieren, wenn Sie über die Enterprise Plus Lizenz von VMware verfügen.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-BB5D9BAB-9E0E-4204-A76A-54634CD8AD51.html["Dokumentation zu VMware vSphere: Storage I/O Control ermöglichen"^]

Im VSC Dashboard werden IOPS, der genutzte Speicherplatz, die Latenz und die engagierte Kapazität, die über den vCenter Server bezogen werden, angezeigt. ONTAP bietet im VSC Dashboard Metriken zur Speicherersparnis auf dem Volume. Mit diesen Performance-Parametern können Sie Performance-Engpässe in der virtuellen Umgebung identifizieren und Korrekturmaßnahmen ergreifen, um die Probleme zu beheben.

Im herkömmlichen Dashboard der virtuellen Appliance für VSC, VASA Provider und SRA können Sie entweder NFS-Datastores oder VMFS-Datastores anzeigen. Sie können auf einen Datastore klicken, um zur Detailansicht des Datastores zu navigieren, die von der vCenter Server-Instanz bereitgestellt wird, um Probleme mit den Datastores in Ihrem vCenter Server anzuzeigen und zu beheben.

.Schritte
. Klicken Sie auf der vSphere Client-Startseite auf *Virtual Storage Console*.
. Wählen Sie den gewünschten vCenter Server aus, indem Sie das Dropdown-Menü *vCenter Server* verwenden, um die Datenspeicher anzuzeigen.
. Klicken Sie Auf *Traditionelles Dashboard*.
+
Das Portlet *Datastores* enthält folgende Details:

+
** Die Anzahl herkömmlicher Datastores mit ihren Performance-Metriken, die von VSC in Ihrer vCenter Server Instanz gemanagt werden
** Die fünf wichtigsten Datastores basierend auf Ressourcennutzung und Performance-Parametern, die geändert werden können. Sie können bei Bedarf die Liste der Datenspeicher basierend auf dem genutzten Speicherplatz, den IOPS oder der Latenz und der erforderlichen Reihenfolge ändern.


+
Das Portlet *Virtual Machines* enthält folgende Details:

+
** Anzahl der Virtual Machines, die NetApp Datastores in Ihrem vCenter Server verwenden
** Die fünf wichtigsten Virtual Machines, basierend auf hoher Kapazität, Latenz und Uptime



