---
permalink: manage/task-remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: removing, storage, from, a, vvols, datastore, 
summary: 'Wenn ein VMware Virtual Volumes (VVols) Datastore mehrere FlexVol Volumes enthält, können Sie eine oder mehrere der FlexVol Volumes aus dem VVols-Datastore entfernen, ohne den Datastore zu löschen.' 
---
= Entfernen Sie Storage aus einem VVols Datastore
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein VMware Virtual Volumes (VVols) Datastore mehrere FlexVol Volumes enthält, können Sie eine oder mehrere der FlexVol Volumes aus dem VVols-Datastore entfernen, ohne den Datastore zu löschen.

.Über diese Aufgabe
Ein VVols-Datastore ist vorhanden, bis mindestens ein FlexVol-Volume auf dem Datastore vorhanden ist.

.Schritte
. Klicken Sie auf der Seite vSphere Client *Home* auf *Hosts und Cluster*.
. Klicken Sie mit der rechten Maustaste auf den VVols-Datastore, den Sie ändern möchten, und wählen Sie dann Menü:NetApp VSC[Entfernen von Storage aus vVol Datastore].
+
Das Dialogfeld *Speicherung aus vVol Datastore* entfernen wird angezeigt.

. Wählen Sie die FlexVol-Volumes aus, die Sie aus dem VVols-Datastore entfernen möchten, und klicken Sie auf *Entfernen*.
. Klicken Sie im Bestätigungsdialogfeld auf *OK*.
+
[NOTE]
====
Wenn Sie alle FlexVol-Volumes auswählen, wird eine Fehlermeldung angezeigt, die angibt, dass der Vorgang fehlschlägt.

====

